### ISSUE TITLE
eval == evil

### ISSUE THREAD

**Issue by johnnyshields** [gimite/moji#3]
Is it possible to make a version of Moji which does not use eval? (Maybe dropping support for Ruby < 1.9 would be necessary?)

**Comment by gimite** [comment]
What's the reason you want to avoid eval? Ruby 1.8 is still widely used, so I don't want to drop its support. So it would be tricky to avoid eval. Please let me know if you have good idea.

**Comment by johnnyshields** [comment]
Mainly eval makes it difficult for debugging. Recently I had a charset issue which was difficult to see where the error was occuring. There are also potential security concerns and performance issues, but I not sure if that applies to Moji.

Possibly you could have Moji version 1.x-stable to support Ruby 1.8, and add a new version 2.x-stable which is >=1.9 only.

**Comment by gimite** [comment]
> Mainly eval makes it difficult for debugging. Recently I had a charset issue which was difficult to see where the error was occuring.

That's good point. I have just pushed a change to add filename and lineno arguments to eval() so that stack trace shows correct line number. (Not in gem yet, though.)

> Possibly you could have Moji version 1.x-stable to support Ruby 1.8, and add a new version 2.x-stable which is >=1.9 only.

It makes maintenance harder, so I want to avoid it unless there is strong reason.

**Comment by johnnyshields** [comment]
http://www.ruby-lang.org/ja/news/2013/06/30/we-retire-1-8-7/

**Comment by johnnyshields** [comment]
@gimite can you please reconsider now that 1.9.3 is end-of-life? Let's make a new version of Moji which supports only 2.0.0+, so we can get rid of legacy syntax.

**Comment by gimite** [comment]
With the change I made above, I don't think of strong reason to avoid eval, especially considering the library is in maintenance mode, with almost no changes in these a few years.
